# Generated by Django 4.2.1 on 2024-03-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='useAt',
            new_name='used_at',
        ),
    ]
