providers = ["python"]

[phases.setup]
nixPkgs = ["python39", "postgresql_16", "pipenv", "gcc"]

[phases.install]
cmds = ["pipenv install --system --deploy"]

[start]
cmd = "python manage.py migrate && gunicorn core.wsgi"