[phases.setup]
nixPkgs = ["gcc", "pipenv", "postgresql_16", "python39"]

[phases.install]
cmds = ["pipenv install --deploy"]

[start]
cmd = "pipenv run python manage.py migrate && pipenv run gunicorn core.wsgi"